spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:4000/wiki?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          CharSet: utf8
          useUnicode: true
          characterEncoding: utf-8
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true